%YAML:1.0

#common parameters
#support: 1 imu 1 cam; 1 imu 2 cam: 2 cam; 
imu: 0         
num_of_cam: 2  

imu_topic: "none"
image0_topic: "/left_cam/image_raw"
image1_topic: "/right_cam/image_raw"
output_path: "/mnt/DATA/"

cam0_calib: "cam0_pinhole_v3.yaml"
cam1_calib: "cam1_pinhole_v3.yaml"
image_width: 480
image_height: 640
   

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 0   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.

body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [1, 0, 0, 0,
          0, 1, 0, 0,
          0, 0, 1, 0,
          0, 0, 0, 1]

body_T_cam1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [0.998564761370902, -0.0384244457624412, 0.0373092390182685,  0.0934589857810588,
          0.0361317642700212,  0.997526546245566, 0.0602933258837887,  0.00364333327441903,
          -0.0395336939712026, -0.0588587419441015, 0.997483200629338, -0.00804274342105135,
          0, 0, 0, 1]
#   [0.998564761370902,  0.0361317642700212,  -0.0395336939712025, -0.0937744492505547,
# -0.0384244457624412, 0.997526546245566, -0.0588587419441016, -0.000516597687437984,  
# 0.0373092390182686,  0.0602933258837887,  0.997483200629339, 0.00431594913014257,
#          0, 0, 0, 1]

#Multiple thread support
multiple_thread: 1

#feature traker paprameters
max_cnt: 150            # max feature number in feature tracking
min_dist: 30            # min distance between two features 
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1 # 0 #     # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)
