%YAML:1.0

#common parameters
#support: 1 imu 1 cam; 1 imu 2 cam: 2 cam; 
imu: 0         
num_of_cam: 2  

imu_topic: "none"
image0_topic: "/left_cam/image_raw"
image1_topic: "/right_cam/image_raw"
output_path: "/mnt/DATA/"

cam0_calib: "hololens-left_camera_calib.yaml"
cam1_calib: "hololens-right_camera_calib.yaml"
image_width: 480
image_height: 640
   

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 0   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.

body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [1, 0, 0, 0,
          0, 1, 0, 0,
          0, 0, 1, 0,
          0, 0, 0, 1]

body_T_cam1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [0.998109019818906, 0.0352349404232186,  -0.0503674848440523, 0.0943913017040972,
          -0.0357609409145917, 0.999314452082774, -0.00958023817073695,  -0.00179839355977732,
          0.0499953963985354,  0.0113633107797507,  0.998684802881808, -4.58145760742406e-05,
          0, 0, 0, 1]

#Multiple thread support
multiple_thread: 1

#feature traker paprameters
max_cnt: 150            # max feature number in feature tracking
min_dist: 20 # 30 #           # min distance between two features 
freq: 0 # 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 0 # 1 #     # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)
