%YAML:1.0

#common parameters
#support: 1 imu 1 cam; 1 imu 2 cam: 2 cam; 
imu: 0         
num_of_cam: 2  

imu_topic: "none"
image0_topic: "/snappy_cam/stereo_l"
image1_topic: "/snappy_cam/stereo_r"
output_path: "/mnt/DATA/"

cam0_calib: "cam0_pinhole.yaml"
cam1_calib: "cam1_pinhole.yaml"
image_width: 640
image_height: 480
   

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 0   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.

body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [-0.0143133880694228,  0.0588356558618825,  0.998165062763309, 0.00762288700220483,
           -0.999885603124687,  -0.00572378030906160,  -0.0140006786606730, 0.0298932758831561,
           0.00488953841992569, -0.998251272945985,  0.0589108519354824,  -0.0271729686907363,
           0.0, 0.0, 0.0, 1.0]

body_T_cam1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [0.0474731185485422, 0.0542327524629761,  0.997399173638902, 0.00900513174877429,
           -0.998857295295489,  0.00808976877719030, 0.0471026461688963,  -0.0487886758650137,
           -0.00551422254327056,  -0.998495550416436,  0.0545548269937878,  -0.0272543170815127,
           0.0, 0.0, 0.0, 1.0]

#Multiple thread support
multiple_thread: 1

#feature traker paprameters
max_cnt: 200            # max feature number in feature tracking
min_dist: 20 # 30            # min distance between two features 
freq: 0 # 10            # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 0 # 1       # publish tracking image as topic
flow_back: 1 # 0        # perform forward and backward optical flow to improve feature tracking accuracy

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)
